[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-add",
    "allow-add-credential",
    "allow-add-remote",
    "allow-branch",
    "allow-checkout",
    "allow-commit",
    "allow-delete-branch",
    "allow-fetch-all",
    "allow-initialize",
    "allow-log",
    "allow-merge-branch",
    "allow-pull",
    "allow-push",
    "allow-remotes",
    "allow-rm-remote",
    "allow-status",
    "allow-unstage",
]
